#!/usr/bin/env bash

set -e -o pipefail -u

timestamp=$(date +%s)
cast=/tmp/${timestamp}.cast
gif=/tmp/${timestamp}.gif

spoonfeed() {
  init_delay=$1
  sleep $init_delay

  text=$2
  comp=
  buffer=
  for (( i=0; i<${#text}; i++ )); do
    char=${text:$i:1}
    if [[ $char == '^' ]]; then
      sleep 0.5
      continue
    elif [[ $char == '~' ]]; then
      comp=true
      char=
    elif [[ $char == ' ' || $char == '=' ]]; then
      comp=
    fi
    buffer="${buffer}${char}"
    if ! [[ $comp ]]; then
      echo -n "$buffer"
      buffer=
      sleep 0.15
    fi
  done
  echo "$buffer"
}

function script() {
  spoonfeed 2 'git ma~chete dis~cover --ch~ecked-out-since="2 weeks ago"'
  spoonfeed 3 'y^'
  spoonfeed 3 '~clear'

  spoonfeed 1 'git ma~chete st~atus --l~ist-commits'
  spoonfeed 4 '~clear'

  spoonfeed 1 'git chec~kout d~evelop'
  spoonfeed 1 'git ma~chete tr~averse'
  spoonfeed 3 'y^'
  spoonfeed 3 'yq^'
  spoonfeed 2 '~clear'

  spoonfeed 1 'git ma~chete st~atus --l~ist-commits'
  spoonfeed 4 '~clear'

  spoonfeed 1 'git ma~chete tr~averse'
  spoonfeed 3 'y^'
  spoonfeed 3 'yq^'
  spoonfeed 5 '~clear'
  spoonfeed 1 '~exit'
}

init_contents='set -e -o pipefail -u; PS1=\(\\\$\(date\ +%H:%M:%S\)\)\ \$\ ; export GIT_MACHETE_DIM_AS_GRAY=true; export GIT_SEQUENCE_EDITOR=:'
nested_command="bash --init-file <(echo '$init_contents')"
script | asciinema rec --command="bash -c \"$nested_command\"" "$cast"
# `head -n -3` to remove the 3 final lines responsible for the terminating `exit`
# Note: for some reason, the resulting gif manifested weird behavior for widths lower than 120;
# I needed to crop the right margin in an external tool.
asciicast2gif -s 1 -S 0.75 -w 120 -h 35 <(head -n -3 "$cast") "$gif"
echo "$gif"
eog "$gif"
