---
plugins:
  validate-links:
  lint-no-dead-urls:
    skipUrlPatterns: ['/https:\/\/img\.shields\.io/',
                      'https://github.com/r-ryantm',
                      'https://pypistats.org/packages/git-machete']
    gotOptions.timeout: 60000
