#!/usr/bin/env bash

_git_machete() {
	cmds="add d diff down e edit file fork-point format g go help next prev prune-branches reapply root slide-out s status traverse up update"
	common_opts="-h --help -v --verbose"
	add_opts="-o --onto"
	diff_opts="-s --stat"
	reapply_opts="-f --fork-point"
	slide_out_opts="-d --down-fork-point"
	status_opts="-l --list-commits -r --remote"
	traverse_opts="-l --list-commits -r --remote"
	update_opts="-f --fork-point"
	directions="down next prev root up"

	prev="${COMP_WORDS[COMP_CWORD-1]}"

	if [[ ${cur} == -* ]] ; then
		case "$prev" in
			add) __gitcomp "$common_opts $add_opts" ;;
			d|diff) __gitcomp "$common_opts $diff_opts" ;;
			reapply) __gitcomp "$common_opts $reapply_opts" ;;
			slide-out) __gitcomp "$common_opts $slide_out_opts" ;;
			s|status) __gitcomp "$common_opts $status_opts" ;;
			traverse) __gitcomp "$common_opts $traverse_opts" ;;
			update) __gitcomp "$common_opts $update_opts" ;;
			*) __gitcomp "$common_opts" ;;
		esac
	elif [[ ${#COMP_WORDS[@]} -eq 3 ]]; then
		__gitcomp "$cmds"
	else
		case "$prev" in
			g|go) __gitcomp "$directions" ;;
			help|--help|-h) __gitcomp "$cmds" ;;
			add|d|diff|down|fork-point|next|-o|--onto|prev|root|slide-out|up) __gitcomp_nl "$(__git_heads)" ;;
			-r|--remote) __gitcomp_nl "$(__git_remotes)" ;;
			-d|--down-fork-point|-f|--fork-point) __gitcomp_nl "$(__git_refs)" ;;
			*)
			    if [[ "${COMP_WORDS[2]}" == slide-out ]]; then
			        __gitcomp_nl "$(__git_heads)"
			    else
			        COMPREPLY=()
			    fi
			    ;;
		esac
	fi
}
