#!/usr/bin/env bash

_git_machete() {
	cmds="add anno d delete-unmanaged diff discover e edit file fork-point format g go help infer l list log prune-branches reapply show slide-out s status traverse update"
	categories="managed slidable slidable-after unmanaged"
	directions="down first last next prev root up"

	common_opts="--debug -h --help -v --verbose --version"
	add_opts="-o --onto"
	diff_opts="-s --stat"
	discover_opts="-l --list-commits"
	infer_opts="-l --list-commits"
	reapply_opts="-f --fork-point"
	slide_out_opts="-d --down-fork-point"
	status_opts="-l --list-commits"
	traverse_opts="-l --list-commits"
	update_opts="-f --fork-point"

	prev="${COMP_WORDS[COMP_CWORD-1]}"

	if [[ "$cur" == -* ]] ; then
		case "$prev" in
			add) __gitcomp "$common_opts $add_opts" ;;
			d|diff) __gitcomp "$common_opts $diff_opts" ;;
			discover) __gitcomp "$common_opts $discover_opts" ;;
			infer) __gitcomp "$common_opts $infer_opts" ;;
			reapply) __gitcomp "$common_opts $reapply_opts" ;;
			slide-out) __gitcomp "$common_opts $slide_out_opts" ;;
			s|status) __gitcomp "$common_opts $status_opts" ;;
			traverse) __gitcomp "$common_opts $traverse_opts" ;;
			update) __gitcomp "$common_opts $update_opts" ;;
			*) __gitcomp "$common_opts" ;;
		esac
	elif [[ "$COMP_CWORD" -eq 2 ]]; then
		__gitcomp "$cmds"
	else
		case "$prev" in
			-d|--down-fork-point|-f|--fork-point) __gitcomp "$(__git_refs)" ;;
			-h|--help) __gitcomp "$cmds" ;;
			-o|--onto) __gitcomp_nl "$(git machete list managed)" ;;
			*)
				case "${COMP_WORDS[2]}" in
					add) __gitcomp_nl "$(git machete list unmanaged)" ;;
					d|diff|fork-point|l|log) __gitcomp "$(__git_heads)" ;;
					g|go|show) __gitcomp "$directions" ;;
					help) __gitcomp "$cmds" ;;
					list)
					    if [[ "$COMP_CWORD" -eq 3 ]]; then
					        __gitcomp "$categories"
					    elif [[ "$COMP_CWORD" -eq 4 ]] && [[ "$prev" == "slidable-after" ]]; then
					        __gitcomp_nl "$(git machete list slidable)"
					    fi ;;
					slide-out)
						if [[ "$COMP_CWORD" -eq 3 ]]; then
							__gitcomp_nl "$(git machete list slidable)"
						else
							__gitcomp_nl "$(git machete list slidable-after "$prev" 2>/dev/null)"
						fi ;;
					*) COMPREPLY=() ;;
				esac ;;
		esac
	fi
}
