#!/usr/bin/env bash

if [[ $OSTYPE == darwin* ]]; then
  wrap0_flag=""
else
  wrap0_flag="--wrap=0"
fi

export GPG_PRIVATE_KEY_PASSPHRASE=$(cat ~/.gnupg/passphrase.txt)
export GPG_PRIVATE_KEY_CONTENTS_BASE64=$(base64 $wrap0_flag < ~/.gnupg/private.key)
export SSH_PRIVATE_KEY_CONTENTS_BASE64=$(base64 $wrap0_flag < ~/.ssh/id_rsa)
