version: '3'
services:
  rpm:
    image: gitmachete/ci-rpm:${DIRECTORY_HASH:-unspecified}
    build:
      context: build-context
      dockerfile: ../Dockerfile # relative to build-context
    volumes:
      # Host path is relative to current directory, not build-context
      - ./../..:/git-machete
