version: '3'
services:
  rpm:
    image: gitmachete/ci-rpm:${DIRECTORY_HASH:-unspecified}
    build:
      context: build-context
      dockerfile: ../Dockerfile # relative to build-context
      target: ${TARGET:-circle_ci}
      args:
        - user_id=${USER_ID:-0}
        - group_id=${GROUP_ID:-0}
    volumes:
      # Host path is relative to current directory, not build-context
      - ./../..:${MOUNT_POINT:-/root}/git-machete
