version: '3'
services:
  nixpkgs-build:
    image: gitmachete/ci-nixpkgs-build:${DIRECTORY_HASH:-unspecified}
    build:
      context: build-context
      dockerfile: ../Dockerfile # relative to build-context
    tty: true
    environment:
      - GIT_REVISION
