name: git-machete3
summary: git-machete is a versatile tool for organizing your git repo
description: |
  git machete is a versatile tool for organizing your git repo, including features like:
  - Neat, customizable `git machete status` that shows what branches are in sync with their parent branch/remote tracking branch and which of them need to be rebased/merged/pulled/pushed
  - Semi-automatic `git machete traverse` through the branches that helps you effortlessly rebase/merge and push/pull the branches you care for
  - Automatic discovery of branch relations (`git machete discover`)
adopt-info: git-machete3
grade: stable
# See https://forum.snapcraft.io/t/-/15566 for discussion on why classic confinement was necessary.
confinement: strict
icon: graphics/logo.png
license: MIT
base: core18
architectures:
  # See https://forum.snapcraft.io/t/how-can-i-publish-a-snap-that-can-provide-binaries-for-all-the-supported-architectures/8556/4
  # on why not just `build-on: [ amd64, i386 ]`.
  - build-on: [i386, amd64]

apps:
  git-machete3:
    command: bin/git-machete
    plugs: [home, network, network-bind, removable-media]

parts:
  git-machete3:
    plugin: python
    source-branch: build/snap
    source: https://github.com/VirtusLab/git-machete.git
    source-type: git
    # We're setting the version via scriptlet rather than using `version: git`
    # since only pushing commits to master (and not pushing tags) triggers Snapcraft builds.
    override-build: |
      set -x
      echo dziala
      snapcraftctl build
      version="$(python3 setup.py --version)"
      snapcraftctl set-version "$version"
