name: git-machete
summary: git-machete is a versatile tool for organizing your git repo
description: |
  git machete is a versatile tool for organizing your git repo, including features like:
  - Neat, customizable `git machete status` that shows what branches are in sync with their parent branch/remote tracking branch and which of them need to be rebased/merged/pulled/pushed
  - Semi-automatic `git machete traverse` through the branches that helps you effortlessly rebase/merge and push/pull the branches you care for
  - Automatic discovery of branch relations (`git machete discover`)
adopt-info: git-machete
grade: stable
# See https://forum.snapcraft.io/t/-/15566 for discussion on why classic confinement was necessary.
confinement: classic
icon: graphics/logo.png
license: MIT
base: core18
architectures:
  - build-on: [i386, amd64]

apps:
  git-machete:
    command: bin/git-machete

parts:
  git-machete:
    plugin: python
    source: .
    # We're setting the version via scriptlet rather than using `version: git`
    # since only pushing commits to master (and not pushing tags) triggers Snapcraft builds.
    override-build: |
      set -x
      snapcraftctl build
      version="$(python3 setup.py --version)"
      snapcraftctl set-version "$version"
