name: git-machete
summary: git-machete is a versatile tool for organizing your git repo
description: |
  git machete is a versatile tool for organizing your git repo, including features like:
  - Neat, customizable `git machete status` that shows what branches are in sync with their parent branch/remote tracking branch and which of them need to be rebased/merged/pulled/pushed
  - Semi-automatic `git machete traverse` through the branches that helps you effortlessly rebase/merge and push/pull the branches you care for
  - Automatic discovery of branch relations (`git machete discover`)
version: '3.8.0'
grade: stable
confinement: strict
base: core20
architectures:
  - build-on: [i386, amd64]

apps:
  git-machete:
    command: bin/git-machete
    plugs: [home, network, network-bind, removable-media]

parts:
  git-machete:
    plugin: python
    source-branch: build/snap
    source: https://github.com/VirtusLab/git-machete.git